// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: data_handler.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_Movie MediaType = 0
	MediaType_Serie MediaType = 1
	MediaType_Both  MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "Movie",
		1: "Serie",
		2: "Both",
	}
	MediaType_value = map[string]int32{
		"Movie": 0,
		"Serie": 1,
		"Both":  2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_handler_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_data_handler_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{0}
}

type FilterBy int32

const (
	FilterBy_fav    FilterBy = 0
	FilterBy_viewed FilterBy = 1
)

// Enum value maps for FilterBy.
var (
	FilterBy_name = map[int32]string{
		0: "fav",
		1: "viewed",
	}
	FilterBy_value = map[string]int32{
		"fav":    0,
		"viewed": 1,
	}
)

func (x FilterBy) Enum() *FilterBy {
	p := new(FilterBy)
	*p = x
	return p
}

func (x FilterBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterBy) Descriptor() protoreflect.EnumDescriptor {
	return file_data_handler_proto_enumTypes[1].Descriptor()
}

func (FilterBy) Type() protoreflect.EnumType {
	return &file_data_handler_proto_enumTypes[1]
}

func (x FilterBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterBy.Descriptor instead.
func (FilterBy) EnumDescriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{1}
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Genres        string                 `protobuf:"bytes,5,opt,name=genres,proto3" json:"genres,omitempty"`
	Seasons       int32                  `protobuf:"varint,6,opt,name=seasons,proto3" json:"seasons,omitempty"`
	Caps          int32                  `protobuf:"varint,7,opt,name=caps,proto3" json:"caps,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Rating        int32                  `protobuf:"varint,9,opt,name=rating,proto3" json:"rating,omitempty"`
	Image         string                 `protobuf:"bytes,10,opt,name=image,proto3" json:"image,omitempty"`
	Fav           bool                   `protobuf:"varint,11,opt,name=fav,proto3" json:"fav,omitempty"`
	Viewed        bool                   `protobuf:"varint,12,opt,name=viewed,proto3" json:"viewed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_data_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{0}
}

func (x *Media) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Media) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Media) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Media) GetGenres() string {
	if x != nil {
		return x.Genres
	}
	return ""
}

func (x *Media) GetSeasons() int32 {
	if x != nil {
		return x.Seasons
	}
	return 0
}

func (x *Media) GetCaps() int32 {
	if x != nil {
		return x.Caps
	}
	return 0
}

func (x *Media) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Media) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Media) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Media) GetFav() bool {
	if x != nil {
		return x.Fav
	}
	return false
}

func (x *Media) GetViewed() bool {
	if x != nil {
		return x.Viewed
	}
	return false
}

type MediaResume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Genres        string                 `protobuf:"bytes,4,opt,name=genres,proto3" json:"genres,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Fav           bool                   `protobuf:"varint,7,opt,name=fav,proto3" json:"fav,omitempty"`
	Viewed        bool                   `protobuf:"varint,8,opt,name=viewed,proto3" json:"viewed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaResume) Reset() {
	*x = MediaResume{}
	mi := &file_data_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaResume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaResume) ProtoMessage() {}

func (x *MediaResume) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaResume.ProtoReflect.Descriptor instead.
func (*MediaResume) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{1}
}

func (x *MediaResume) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MediaResume) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaResume) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MediaResume) GetGenres() string {
	if x != nil {
		return x.Genres
	}
	return ""
}

func (x *MediaResume) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MediaResume) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MediaResume) GetFav() bool {
	if x != nil {
		return x.Fav
	}
	return false
}

func (x *MediaResume) GetViewed() bool {
	if x != nil {
		return x.Viewed
	}
	return false
}

type LastUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MediaType              `protobuf:"varint,1,opt,name=type,proto3,enum=data_handler.MediaType" json:"type,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastUpdatesRequest) Reset() {
	*x = LastUpdatesRequest{}
	mi := &file_data_handler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastUpdatesRequest) ProtoMessage() {}

func (x *LastUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastUpdatesRequest.ProtoReflect.Descriptor instead.
func (*LastUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{2}
}

func (x *LastUpdatesRequest) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_Movie
}

func (x *LastUpdatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaRequest) Reset() {
	*x = MediaRequest{}
	mi := &file_data_handler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRequest) ProtoMessage() {}

func (x *MediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaRequest.ProtoReflect.Descriptor instead.
func (*MediaRequest) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{3}
}

func (x *MediaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MediaFilteredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        FilterBy               `protobuf:"varint,1,opt,name=filter,proto3,enum=data_handler.FilterBy" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaFilteredRequest) Reset() {
	*x = MediaFilteredRequest{}
	mi := &file_data_handler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaFilteredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaFilteredRequest) ProtoMessage() {}

func (x *MediaFilteredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaFilteredRequest.ProtoReflect.Descriptor instead.
func (*MediaFilteredRequest) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{4}
}

func (x *MediaFilteredRequest) GetFilter() FilterBy {
	if x != nil {
		return x.Filter
	}
	return FilterBy_fav
}

type MediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaResponse) Reset() {
	*x = MediaResponse{}
	mi := &file_data_handler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaResponse) ProtoMessage() {}

func (x *MediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaResponse.ProtoReflect.Descriptor instead.
func (*MediaResponse) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{5}
}

func (x *MediaResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type MediaListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaList     []*MediaResume         `protobuf:"bytes,1,rep,name=mediaList,proto3" json:"mediaList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaListResponse) Reset() {
	*x = MediaListResponse{}
	mi := &file_data_handler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaListResponse) ProtoMessage() {}

func (x *MediaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaListResponse.ProtoReflect.Descriptor instead.
func (*MediaListResponse) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{6}
}

func (x *MediaListResponse) GetMediaList() []*MediaResume {
	if x != nil {
		return x.MediaList
	}
	return nil
}

var File_data_handler_proto protoreflect.FileDescriptor

const file_data_handler_proto_rawDesc = "" +
	"\n" +
	"\x12data_handler.proto\x12\fdata_handler\"\x95\x02\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x16\n" +
	"\x06genres\x18\x05 \x01(\tR\x06genres\x12\x18\n" +
	"\aseasons\x18\x06 \x01(\x05R\aseasons\x12\x12\n" +
	"\x04caps\x18\a \x01(\x05R\x04caps\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\t \x01(\x05R\x06rating\x12\x14\n" +
	"\x05image\x18\n" +
	" \x01(\tR\x05image\x12\x10\n" +
	"\x03fav\x18\v \x01(\bR\x03fav\x12\x16\n" +
	"\x06viewed\x18\f \x01(\bR\x06viewed\"\xc1\x01\n" +
	"\vMediaResume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06genres\x18\x04 \x01(\tR\x06genres\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x10\n" +
	"\x03fav\x18\a \x01(\bR\x03fav\x12\x16\n" +
	"\x06viewed\x18\b \x01(\bR\x06viewed\"W\n" +
	"\x12LastUpdatesRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.data_handler.MediaTypeR\x04type\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x1e\n" +
	"\fMediaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"F\n" +
	"\x14MediaFilteredRequest\x12.\n" +
	"\x06filter\x18\x01 \x01(\x0e2\x16.data_handler.FilterByR\x06filter\":\n" +
	"\rMediaResponse\x12)\n" +
	"\x05media\x18\x01 \x01(\v2\x13.data_handler.MediaR\x05media\"L\n" +
	"\x11MediaListResponse\x127\n" +
	"\tmediaList\x18\x01 \x03(\v2\x19.data_handler.MediaResumeR\tmediaList*+\n" +
	"\tMediaType\x12\t\n" +
	"\x05Movie\x10\x00\x12\t\n" +
	"\x05Serie\x10\x01\x12\b\n" +
	"\x04Both\x10\x02*\x1f\n" +
	"\bFilterBy\x12\a\n" +
	"\x03fav\x10\x00\x12\n" +
	"\n" +
	"\x06viewed\x10\x012\x81\x02\n" +
	"\vDataHandler\x12U\n" +
	"\x0eGetLastUpdates\x12 .data_handler.LastUpdatesRequest\x1a\x1f.data_handler.MediaListResponse\"\x00\x12@\n" +
	"\vGetOneMedia\x12\x1a.data_handler.MediaRequest\x1a\x13.data_handler.Media\"\x00\x12Y\n" +
	"\x10GetMediaFiltered\x12\".data_handler.MediaFilteredRequest\x1a\x1f.data_handler.MediaListResponse\"\x00B1Z/github.com/condemo/movie-hub/common/services/pbb\x06proto3"

var (
	file_data_handler_proto_rawDescOnce sync.Once
	file_data_handler_proto_rawDescData []byte
)

func file_data_handler_proto_rawDescGZIP() []byte {
	file_data_handler_proto_rawDescOnce.Do(func() {
		file_data_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_handler_proto_rawDesc), len(file_data_handler_proto_rawDesc)))
	})
	return file_data_handler_proto_rawDescData
}

var file_data_handler_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_data_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_data_handler_proto_goTypes = []any{
	(MediaType)(0),               // 0: data_handler.MediaType
	(FilterBy)(0),                // 1: data_handler.FilterBy
	(*Media)(nil),                // 2: data_handler.Media
	(*MediaResume)(nil),          // 3: data_handler.MediaResume
	(*LastUpdatesRequest)(nil),   // 4: data_handler.LastUpdatesRequest
	(*MediaRequest)(nil),         // 5: data_handler.MediaRequest
	(*MediaFilteredRequest)(nil), // 6: data_handler.MediaFilteredRequest
	(*MediaResponse)(nil),        // 7: data_handler.MediaResponse
	(*MediaListResponse)(nil),    // 8: data_handler.MediaListResponse
}
var file_data_handler_proto_depIdxs = []int32{
	0, // 0: data_handler.LastUpdatesRequest.type:type_name -> data_handler.MediaType
	1, // 1: data_handler.MediaFilteredRequest.filter:type_name -> data_handler.FilterBy
	2, // 2: data_handler.MediaResponse.media:type_name -> data_handler.Media
	3, // 3: data_handler.MediaListResponse.mediaList:type_name -> data_handler.MediaResume
	4, // 4: data_handler.DataHandler.GetLastUpdates:input_type -> data_handler.LastUpdatesRequest
	5, // 5: data_handler.DataHandler.GetOneMedia:input_type -> data_handler.MediaRequest
	6, // 6: data_handler.DataHandler.GetMediaFiltered:input_type -> data_handler.MediaFilteredRequest
	8, // 7: data_handler.DataHandler.GetLastUpdates:output_type -> data_handler.MediaListResponse
	2, // 8: data_handler.DataHandler.GetOneMedia:output_type -> data_handler.Media
	8, // 9: data_handler.DataHandler.GetMediaFiltered:output_type -> data_handler.MediaListResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_data_handler_proto_init() }
func file_data_handler_proto_init() {
	if File_data_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_handler_proto_rawDesc), len(file_data_handler_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_handler_proto_goTypes,
		DependencyIndexes: file_data_handler_proto_depIdxs,
		EnumInfos:         file_data_handler_proto_enumTypes,
		MessageInfos:      file_data_handler_proto_msgTypes,
	}.Build()
	File_data_handler_proto = out.File
	file_data_handler_proto_goTypes = nil
	file_data_handler_proto_depIdxs = nil
}
