// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: data_handler.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_Movie MediaType = 0
	MediaType_Serie MediaType = 1
	MediaType_Both  MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "Movie",
		1: "Serie",
		2: "Both",
	}
	MediaType_value = map[string]int32{
		"Movie": 0,
		"Serie": 1,
		"Both":  2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_handler_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_data_handler_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{0}
}

type FilterBy int32

const (
	FilterBy_fav        FilterBy = 0
	FilterBy_viewed     FilterBy = 1
	FilterBy_recomended FilterBy = 2
)

// Enum value maps for FilterBy.
var (
	FilterBy_name = map[int32]string{
		0: "fav",
		1: "viewed",
		2: "recomended",
	}
	FilterBy_value = map[string]int32{
		"fav":        0,
		"viewed":     1,
		"recomended": 2,
	}
)

func (x FilterBy) Enum() *FilterBy {
	p := new(FilterBy)
	*p = x
	return p
}

func (x FilterBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterBy) Descriptor() protoreflect.EnumDescriptor {
	return file_data_handler_proto_enumTypes[1].Descriptor()
}

func (FilterBy) Type() protoreflect.EnumType {
	return &file_data_handler_proto_enumTypes[1]
}

func (x FilterBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterBy.Descriptor instead.
func (FilterBy) EnumDescriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{1}
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	FirstAir      int32                  `protobuf:"varint,5,opt,name=firstAir,proto3" json:"firstAir,omitempty"`
	Genres        string                 `protobuf:"bytes,6,opt,name=genres,proto3" json:"genres,omitempty"`
	Seasons       int32                  `protobuf:"varint,7,opt,name=seasons,proto3" json:"seasons,omitempty"`
	Caps          int32                  `protobuf:"varint,8,opt,name=caps,proto3" json:"caps,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Rating        int32                  `protobuf:"varint,10,opt,name=rating,proto3" json:"rating,omitempty"`
	Runtime       int32                  `protobuf:"varint,11,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Image         string                 `protobuf:"bytes,12,opt,name=image,proto3" json:"image,omitempty"`
	Fav           bool                   `protobuf:"varint,13,opt,name=fav,proto3" json:"fav,omitempty"`
	Viewed        bool                   `protobuf:"varint,14,opt,name=viewed,proto3" json:"viewed,omitempty"`
	Recomended    bool                   `protobuf:"varint,15,opt,name=recomended,proto3" json:"recomended,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,16,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_data_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{0}
}

func (x *Media) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Media) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Media) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Media) GetFirstAir() int32 {
	if x != nil {
		return x.FirstAir
	}
	return 0
}

func (x *Media) GetGenres() string {
	if x != nil {
		return x.Genres
	}
	return ""
}

func (x *Media) GetSeasons() int32 {
	if x != nil {
		return x.Seasons
	}
	return 0
}

func (x *Media) GetCaps() int32 {
	if x != nil {
		return x.Caps
	}
	return 0
}

func (x *Media) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Media) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Media) GetRuntime() int32 {
	if x != nil {
		return x.Runtime
	}
	return 0
}

func (x *Media) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Media) GetFav() bool {
	if x != nil {
		return x.Fav
	}
	return false
}

func (x *Media) GetViewed() bool {
	if x != nil {
		return x.Viewed
	}
	return false
}

func (x *Media) GetRecomended() bool {
	if x != nil {
		return x.Recomended
	}
	return false
}

func (x *Media) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

type MediaResume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Genres        string                 `protobuf:"bytes,4,opt,name=genres,proto3" json:"genres,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,6,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Fav           bool                   `protobuf:"varint,7,opt,name=fav,proto3" json:"fav,omitempty"`
	Viewed        bool                   `protobuf:"varint,8,opt,name=viewed,proto3" json:"viewed,omitempty"`
	Recomended    bool                   `protobuf:"varint,9,opt,name=recomended,proto3" json:"recomended,omitempty"`
	Rating        int32                  `protobuf:"varint,10,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaResume) Reset() {
	*x = MediaResume{}
	mi := &file_data_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaResume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaResume) ProtoMessage() {}

func (x *MediaResume) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaResume.ProtoReflect.Descriptor instead.
func (*MediaResume) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{1}
}

func (x *MediaResume) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MediaResume) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaResume) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MediaResume) GetGenres() string {
	if x != nil {
		return x.Genres
	}
	return ""
}

func (x *MediaResume) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MediaResume) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *MediaResume) GetFav() bool {
	if x != nil {
		return x.Fav
	}
	return false
}

func (x *MediaResume) GetViewed() bool {
	if x != nil {
		return x.Viewed
	}
	return false
}

func (x *MediaResume) GetRecomended() bool {
	if x != nil {
		return x.Recomended
	}
	return false
}

func (x *MediaResume) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type MediaUpdateBool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Viewed        bool                   `protobuf:"varint,2,opt,name=viewed,proto3" json:"viewed,omitempty"`
	Fav           bool                   `protobuf:"varint,3,opt,name=fav,proto3" json:"fav,omitempty"`
	Recomended    bool                   `protobuf:"varint,4,opt,name=recomended,proto3" json:"recomended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaUpdateBool) Reset() {
	*x = MediaUpdateBool{}
	mi := &file_data_handler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaUpdateBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaUpdateBool) ProtoMessage() {}

func (x *MediaUpdateBool) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaUpdateBool.ProtoReflect.Descriptor instead.
func (*MediaUpdateBool) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{2}
}

func (x *MediaUpdateBool) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MediaUpdateBool) GetViewed() bool {
	if x != nil {
		return x.Viewed
	}
	return false
}

func (x *MediaUpdateBool) GetFav() bool {
	if x != nil {
		return x.Fav
	}
	return false
}

func (x *MediaUpdateBool) GetRecomended() bool {
	if x != nil {
		return x.Recomended
	}
	return false
}

type LastUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MediaType              `protobuf:"varint,1,opt,name=type,proto3,enum=data_handler.MediaType" json:"type,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastUpdatesRequest) Reset() {
	*x = LastUpdatesRequest{}
	mi := &file_data_handler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastUpdatesRequest) ProtoMessage() {}

func (x *LastUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastUpdatesRequest.ProtoReflect.Descriptor instead.
func (*LastUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{3}
}

func (x *LastUpdatesRequest) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_Movie
}

func (x *LastUpdatesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *LastUpdatesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *LastUpdatesRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type MediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaRequest) Reset() {
	*x = MediaRequest{}
	mi := &file_data_handler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRequest) ProtoMessage() {}

func (x *MediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaRequest.ProtoReflect.Descriptor instead.
func (*MediaRequest) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{4}
}

func (x *MediaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateMediaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMediaReq) Reset() {
	*x = UpdateMediaReq{}
	mi := &file_data_handler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaReq) ProtoMessage() {}

func (x *UpdateMediaReq) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaReq.ProtoReflect.Descriptor instead.
func (*UpdateMediaReq) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMediaReq) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type MediaFilteredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        FilterBy               `protobuf:"varint,1,opt,name=filter,proto3,enum=data_handler.FilterBy" json:"filter,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaFilteredRequest) Reset() {
	*x = MediaFilteredRequest{}
	mi := &file_data_handler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaFilteredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaFilteredRequest) ProtoMessage() {}

func (x *MediaFilteredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaFilteredRequest.ProtoReflect.Descriptor instead.
func (*MediaFilteredRequest) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{6}
}

func (x *MediaFilteredRequest) GetFilter() FilterBy {
	if x != nil {
		return x.Filter
	}
	return FilterBy_fav
}

func (x *MediaFilteredRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type MediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaResponse) Reset() {
	*x = MediaResponse{}
	mi := &file_data_handler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaResponse) ProtoMessage() {}

func (x *MediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaResponse.ProtoReflect.Descriptor instead.
func (*MediaResponse) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{7}
}

func (x *MediaResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type MediaListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaList     []*MediaResume         `protobuf:"bytes,1,rep,name=mediaList,proto3" json:"mediaList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaListResponse) Reset() {
	*x = MediaListResponse{}
	mi := &file_data_handler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaListResponse) ProtoMessage() {}

func (x *MediaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaListResponse.ProtoReflect.Descriptor instead.
func (*MediaListResponse) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{8}
}

func (x *MediaListResponse) GetMediaList() []*MediaResume {
	if x != nil {
		return x.MediaList
	}
	return nil
}

type EmptyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMsg) Reset() {
	*x = EmptyMsg{}
	mi := &file_data_handler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMsg) ProtoMessage() {}

func (x *EmptyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMsg.ProtoReflect.Descriptor instead.
func (*EmptyMsg) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{9}
}

type MediaCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaCount) Reset() {
	*x = MediaCount{}
	mi := &file_data_handler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaCount) ProtoMessage() {}

func (x *MediaCount) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaCount.ProtoReflect.Descriptor instead.
func (*MediaCount) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{10}
}

func (x *MediaCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_data_handler_proto protoreflect.FileDescriptor

const file_data_handler_proto_rawDesc = "" +
	"\n" +
	"\x12data_handler.proto\x12\fdata_handler\x1a\x1bgoogle/protobuf/empty.proto\"\x89\x03\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x1a\n" +
	"\bfirstAir\x18\x05 \x01(\x05R\bfirstAir\x12\x16\n" +
	"\x06genres\x18\x06 \x01(\tR\x06genres\x12\x18\n" +
	"\aseasons\x18\a \x01(\x05R\aseasons\x12\x12\n" +
	"\x04caps\x18\b \x01(\x05R\x04caps\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\n" +
	" \x01(\x05R\x06rating\x12\x18\n" +
	"\aruntime\x18\v \x01(\x05R\aruntime\x12\x14\n" +
	"\x05image\x18\f \x01(\tR\x05image\x12\x10\n" +
	"\x03fav\x18\r \x01(\bR\x03fav\x12\x16\n" +
	"\x06viewed\x18\x0e \x01(\bR\x06viewed\x12\x1e\n" +
	"\n" +
	"recomended\x18\x0f \x01(\bR\n" +
	"recomended\x12\x1c\n" +
	"\tthumbnail\x18\x10 \x01(\tR\tthumbnail\"\x81\x02\n" +
	"\vMediaResume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06genres\x18\x04 \x01(\tR\x06genres\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1c\n" +
	"\tthumbnail\x18\x06 \x01(\tR\tthumbnail\x12\x10\n" +
	"\x03fav\x18\a \x01(\bR\x03fav\x12\x16\n" +
	"\x06viewed\x18\b \x01(\bR\x06viewed\x12\x1e\n" +
	"\n" +
	"recomended\x18\t \x01(\bR\n" +
	"recomended\x12\x16\n" +
	"\x06rating\x18\n" +
	" \x01(\x05R\x06rating\"k\n" +
	"\x0fMediaUpdateBool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06viewed\x18\x02 \x01(\bR\x06viewed\x12\x10\n" +
	"\x03fav\x18\x03 \x01(\bR\x03fav\x12\x1e\n" +
	"\n" +
	"recomended\x18\x04 \x01(\bR\n" +
	"recomended\"\xa4\x01\n" +
	"\x12LastUpdatesRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.data_handler.MediaTypeR\x04type\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12\x14\n" +
	"\x05order\x18\x04 \x01(\tR\x05orderB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"\x1e\n" +
	"\fMediaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\x0eUpdateMediaReq\x12)\n" +
	"\x05media\x18\x01 \x01(\v2\x13.data_handler.MediaR\x05media\"k\n" +
	"\x14MediaFilteredRequest\x12.\n" +
	"\x06filter\x18\x01 \x01(\x0e2\x16.data_handler.FilterByR\x06filter\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\":\n" +
	"\rMediaResponse\x12)\n" +
	"\x05media\x18\x01 \x01(\v2\x13.data_handler.MediaR\x05media\"L\n" +
	"\x11MediaListResponse\x127\n" +
	"\tmediaList\x18\x01 \x03(\v2\x19.data_handler.MediaResumeR\tmediaList\"\n" +
	"\n" +
	"\bEmptyMsg\"\"\n" +
	"\n" +
	"MediaCount\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count*+\n" +
	"\tMediaType\x12\t\n" +
	"\x05Movie\x10\x00\x12\t\n" +
	"\x05Serie\x10\x01\x12\b\n" +
	"\x04Both\x10\x02*/\n" +
	"\bFilterBy\x12\a\n" +
	"\x03fav\x10\x00\x12\n" +
	"\n" +
	"\x06viewed\x10\x01\x12\x0e\n" +
	"\n" +
	"recomended\x10\x022\xaa\x04\n" +
	"\vDataHandler\x12U\n" +
	"\x0eGetLastUpdates\x12 .data_handler.LastUpdatesRequest\x1a\x1f.data_handler.MediaListResponse\"\x00\x12@\n" +
	"\vGetOneMedia\x12\x1a.data_handler.MediaRequest\x1a\x13.data_handler.Media\"\x00\x12Y\n" +
	"\x10GetMediaFiltered\x12\".data_handler.MediaFilteredRequest\x1a\x1f.data_handler.MediaListResponse\"\x00\x12C\n" +
	"\vDeleteMedia\x12\x1a.data_handler.MediaRequest\x1a\x16.google.protobuf.Empty\"\x00\x12J\n" +
	"\vUpdateMedia\x12\x1c.data_handler.UpdateMediaReq\x1a\x1b.data_handler.MediaResponse\"\x00\x12Q\n" +
	"\x13UpdateMediaBooleans\x12\x1d.data_handler.MediaUpdateBool\x1a\x19.data_handler.MediaResume\"\x00\x12C\n" +
	"\rGetMediaCount\x12\x16.data_handler.EmptyMsg\x1a\x18.data_handler.MediaCount\"\x00B1Z/github.com/condemo/movie-hub/common/services/pbb\x06proto3"

var (
	file_data_handler_proto_rawDescOnce sync.Once
	file_data_handler_proto_rawDescData []byte
)

func file_data_handler_proto_rawDescGZIP() []byte {
	file_data_handler_proto_rawDescOnce.Do(func() {
		file_data_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_handler_proto_rawDesc), len(file_data_handler_proto_rawDesc)))
	})
	return file_data_handler_proto_rawDescData
}

var file_data_handler_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_data_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_data_handler_proto_goTypes = []any{
	(MediaType)(0),               // 0: data_handler.MediaType
	(FilterBy)(0),                // 1: data_handler.FilterBy
	(*Media)(nil),                // 2: data_handler.Media
	(*MediaResume)(nil),          // 3: data_handler.MediaResume
	(*MediaUpdateBool)(nil),      // 4: data_handler.MediaUpdateBool
	(*LastUpdatesRequest)(nil),   // 5: data_handler.LastUpdatesRequest
	(*MediaRequest)(nil),         // 6: data_handler.MediaRequest
	(*UpdateMediaReq)(nil),       // 7: data_handler.UpdateMediaReq
	(*MediaFilteredRequest)(nil), // 8: data_handler.MediaFilteredRequest
	(*MediaResponse)(nil),        // 9: data_handler.MediaResponse
	(*MediaListResponse)(nil),    // 10: data_handler.MediaListResponse
	(*EmptyMsg)(nil),             // 11: data_handler.EmptyMsg
	(*MediaCount)(nil),           // 12: data_handler.MediaCount
	(*emptypb.Empty)(nil),        // 13: google.protobuf.Empty
}
var file_data_handler_proto_depIdxs = []int32{
	0,  // 0: data_handler.LastUpdatesRequest.type:type_name -> data_handler.MediaType
	2,  // 1: data_handler.UpdateMediaReq.media:type_name -> data_handler.Media
	1,  // 2: data_handler.MediaFilteredRequest.filter:type_name -> data_handler.FilterBy
	2,  // 3: data_handler.MediaResponse.media:type_name -> data_handler.Media
	3,  // 4: data_handler.MediaListResponse.mediaList:type_name -> data_handler.MediaResume
	5,  // 5: data_handler.DataHandler.GetLastUpdates:input_type -> data_handler.LastUpdatesRequest
	6,  // 6: data_handler.DataHandler.GetOneMedia:input_type -> data_handler.MediaRequest
	8,  // 7: data_handler.DataHandler.GetMediaFiltered:input_type -> data_handler.MediaFilteredRequest
	6,  // 8: data_handler.DataHandler.DeleteMedia:input_type -> data_handler.MediaRequest
	7,  // 9: data_handler.DataHandler.UpdateMedia:input_type -> data_handler.UpdateMediaReq
	4,  // 10: data_handler.DataHandler.UpdateMediaBooleans:input_type -> data_handler.MediaUpdateBool
	11, // 11: data_handler.DataHandler.GetMediaCount:input_type -> data_handler.EmptyMsg
	10, // 12: data_handler.DataHandler.GetLastUpdates:output_type -> data_handler.MediaListResponse
	2,  // 13: data_handler.DataHandler.GetOneMedia:output_type -> data_handler.Media
	10, // 14: data_handler.DataHandler.GetMediaFiltered:output_type -> data_handler.MediaListResponse
	13, // 15: data_handler.DataHandler.DeleteMedia:output_type -> google.protobuf.Empty
	9,  // 16: data_handler.DataHandler.UpdateMedia:output_type -> data_handler.MediaResponse
	3,  // 17: data_handler.DataHandler.UpdateMediaBooleans:output_type -> data_handler.MediaResume
	12, // 18: data_handler.DataHandler.GetMediaCount:output_type -> data_handler.MediaCount
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_data_handler_proto_init() }
func file_data_handler_proto_init() {
	if File_data_handler_proto != nil {
		return
	}
	file_data_handler_proto_msgTypes[3].OneofWrappers = []any{}
	file_data_handler_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_handler_proto_rawDesc), len(file_data_handler_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_handler_proto_goTypes,
		DependencyIndexes: file_data_handler_proto_depIdxs,
		EnumInfos:         file_data_handler_proto_enumTypes,
		MessageInfos:      file_data_handler_proto_msgTypes,
	}.Build()
	File_data_handler_proto = out.File
	file_data_handler_proto_goTypes = nil
	file_data_handler_proto_depIdxs = nil
}
