// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: data_handler.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_Movie MediaType = 0
	MediaType_Serie MediaType = 1
	MediaType_Both  MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "Movie",
		1: "Serie",
		2: "Both",
	}
	MediaType_value = map[string]int32{
		"Movie": 0,
		"Serie": 1,
		"Both":  2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_handler_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_data_handler_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{0}
}

type LastUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MediaType              `protobuf:"varint,1,opt,name=type,proto3,enum=data_handler.MediaType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastUpdatesRequest) Reset() {
	*x = LastUpdatesRequest{}
	mi := &file_data_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastUpdatesRequest) ProtoMessage() {}

func (x *LastUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastUpdatesRequest.ProtoReflect.Descriptor instead.
func (*LastUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{0}
}

func (x *LastUpdatesRequest) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_Movie
}

type MediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaResponse) Reset() {
	*x = MediaResponse{}
	mi := &file_data_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaResponse) ProtoMessage() {}

func (x *MediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaResponse.ProtoReflect.Descriptor instead.
func (*MediaResponse) Descriptor() ([]byte, []int) {
	return file_data_handler_proto_rawDescGZIP(), []int{1}
}

func (x *MediaResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_data_handler_proto protoreflect.FileDescriptor

const file_data_handler_proto_rawDesc = "" +
	"\n" +
	"\x12data_handler.proto\x12\fdata_handler\"A\n" +
	"\x12LastUpdatesRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.data_handler.MediaTypeR\x04type\"!\n" +
	"\rMediaResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg*+\n" +
	"\tMediaType\x12\t\n" +
	"\x05Movie\x10\x00\x12\t\n" +
	"\x05Serie\x10\x01\x12\b\n" +
	"\x04Both\x10\x022`\n" +
	"\vDataHandler\x12Q\n" +
	"\x0eGetLastUpdates\x12 .data_handler.LastUpdatesRequest\x1a\x1b.data_handler.MediaResponse\"\x00B1Z/github.com/condemo/movie-hub/common/services/pbb\x06proto3"

var (
	file_data_handler_proto_rawDescOnce sync.Once
	file_data_handler_proto_rawDescData []byte
)

func file_data_handler_proto_rawDescGZIP() []byte {
	file_data_handler_proto_rawDescOnce.Do(func() {
		file_data_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_handler_proto_rawDesc), len(file_data_handler_proto_rawDesc)))
	})
	return file_data_handler_proto_rawDescData
}

var file_data_handler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_handler_proto_goTypes = []any{
	(MediaType)(0),             // 0: data_handler.MediaType
	(*LastUpdatesRequest)(nil), // 1: data_handler.LastUpdatesRequest
	(*MediaResponse)(nil),      // 2: data_handler.MediaResponse
}
var file_data_handler_proto_depIdxs = []int32{
	0, // 0: data_handler.LastUpdatesRequest.type:type_name -> data_handler.MediaType
	1, // 1: data_handler.DataHandler.GetLastUpdates:input_type -> data_handler.LastUpdatesRequest
	2, // 2: data_handler.DataHandler.GetLastUpdates:output_type -> data_handler.MediaResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_data_handler_proto_init() }
func file_data_handler_proto_init() {
	if File_data_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_handler_proto_rawDesc), len(file_data_handler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_handler_proto_goTypes,
		DependencyIndexes: file_data_handler_proto_depIdxs,
		EnumInfos:         file_data_handler_proto_enumTypes,
		MessageInfos:      file_data_handler_proto_msgTypes,
	}.Build()
	File_data_handler_proto = out.File
	file_data_handler_proto_goTypes = nil
	file_data_handler_proto_depIdxs = nil
}
